### ISSUE TITLE
App Exit error, App continuosly runs in background and when I exit from app, it stills keeps running on background.

### ISSUE THREAD

**Issue by prateekmedia** [FrendyApp/app_uninstaller#2]
# Final LOGS, other info are in the title itself
```
D/AndroidRuntime(26882): Shutting down VM
E/AndroidRuntime(26882): FATAL EXCEPTION: main
E/AndroidRuntime(26882): Process: com.example.debug, PID: 26882
E/AndroidRuntime(26882): kotlin.NotImplementedError: An operation is not implemented: Not yet implemented
E/AndroidRuntime(26882): 	at com.frendyapp.app_uninstaller.AppUninstallerPlugin.onDetachedFromActivity(AppUninstallerPlugin.kt:80)
E/AndroidRuntime(26882): 	at io.flutter.embedding.engine.FlutterEnginePluginRegistry.detachFromActivity(FlutterEnginePluginRegistry.java:346)
E/AndroidRuntime(26882): 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onDetach(FlutterActivityAndFragmentDelegate.java:512)
E/AndroidRuntime(26882): 	at io.flutter.embedding.android.FlutterActivity.onDestroy(FlutterActivity.java:577)
E/AndroidRuntime(26882): 	at android.app.Activity.performDestroy(Activity.java:8217)
E/AndroidRuntime(26882): 	at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1342)
E/AndroidRuntime(26882): 	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:5311)
E/AndroidRuntime(26882): 	at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:5360)
E/AndroidRuntime(26882): 	at android.app.servertransaction.DestroyActivityItem.execute(DestroyActivityItem.java:44)
E/AndroidRuntime(26882): 	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
E/AndroidRuntime(26882): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
E/AndroidRuntime(26882): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2216)
E/AndroidRuntime(26882): 	at android.os.Handler.dispatchMessage(Handler.java:107)
E/AndroidRuntime(26882): 	at android.os.Looper.loop(Looper.java:237)
E/AndroidRuntime(26882): 	at android.app.ActivityThread.main(ActivityThread.java:7948)
E/AndroidRuntime(26882): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(26882): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/AndroidRuntime(26882): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1075)
```

I have used many libraries in my app but on the exit it says your library name with some kotlin unimplemented error.

**Comment by prateekmedia** [comment]
Maybe the error is talking about this line https://github.com/CodersTurf/app_uninstaller/blob/e1111740faa6d4084395e2086d4f60fff2a2fbcc/android/src/main/kotlin/com/frendyapp/app_uninstaller/AppUninstallerPlugin.kt#L80

**Comment by prateekmedia** [comment]
I have Created and tested the pull request #3, it works as expected now and my app can exit as I wanted, It is a major bug which prevents app from exiting.
